### ISSUE TITLE
Coquille sur la page d'accueil

### ISSUE THREAD

**Issue by minami-o** [nrobinaubertin/zusam#16]
Salut,
Projet très sympa découvert grâce à LinuxFR, j'aime beaucoup l'interface simple mais léchée, pas sûr par contre que je parvienne à convaincre mes paresseux d'amis (non-convertis à xmpp, par exemple) de tenter l'aventure avec moi :)
Je voulais juste remonter une double-coquille sur la page d'accueil en anglais : c'est "Did you forget your password?" et pas "Did you forgot your password ?".
En clair, forgot -> forget, et il n'y a pas d'espace avant le point d'interrogation en anglais.
Bonne continuation !

**Comment by nrobinaubertin** [comment]
Merci !
Je vais corriger la coquille

**Comment by nrobinaubertin** [comment]
Fixed in 6128803c0f30ba0d8d2507ce4207a5af4533c9eb
