### ISSUE TITLE
Cannot invite anyone on 0.3

### ISSUE THREAD

**Issue by briaeros** [nrobinaubertin/zusam#18]
I've test the invitation on the 0.3, and a 500 error code was sent back.
After some times to understand how symfony works, I think that I've pinpointed the bug :
in api/src/Controller/Security.php , ligne 94 : we must change the ligne
`$group = $this->em->getRepository(Group::class)->findOneByInviteKey($inviteKey);`
by
$group = $this->em->getRepository(Group::class)->findOneBySecretKey($inviteKey);
(yes, I'm too lazy to do a PR for a single line)

**Comment by nrobinaubertin** [comment]
Thanks for the finding !
Fixed with 6355b7514bdcef6b3e283ad302c43fe5f1746675
