### ISSUE TITLE
Install  on apache serveur

### ISSUE THREAD

**Issue by treeindark** [nrobinaubertin/zusam#20]
howto configure to use in apache server ?

**Comment by nrobinaubertin** [comment]
Hi,
I wrote a guide to install zusam on debian buster with apache this evening: https://github.com/nrobinaubertin/zusam/blob/0.3.2/documentation/debian-buster-apache.md
If this document does not help, could you give me your distribution (to have a starting point) ?

**Comment by treeindark** [comment]
It's Ok! thx
