### ISSUE TITLE
[Feature request] Register Zusam as a share intent on Android devices

### ISSUE THREAD

**Issue by lmolent** [nrobinaubertin/zusam#3]
Register Zusam as a share intent on Android devices to add option share photos direct from i.e. gallery application or share link from browser etc.
https://chodounsky.net/2019/03/24/progressive-web-application-as-a-share-option-in-android/

**Comment by nrobinaubertin** [comment]
Great idea, thanks for the link !

**Comment by nrobinaubertin** [comment]
Actually, I looked deeper into it and it seems that this API is far away from being supported: https://caniuse.com/#feat=web-share
So let's wait for it to be more widely implemented (chrome + firefox is a minimum)

**Comment by lmolent** [comment]
Yes, it is still not very widely implemented but in android with chrome it works. It looks that currently is only sharing with method GET and text, title and url is implemented (draft looks much better https://wicg.github.io/web-share-target/level-2/#sharetarget-and-its-members). To implement in Zusam is missing only add share_target to manifest.json and add title, text and url GET arguments to `<group_id>/write` or create new method for example `/post?title=&text=&url=` where you will be able to select group to which message will be posted and edit shared content. With this implementation my wife can share photo from Google Photos to Zusam by sharing link, Zusam create preview of this link so photo will be showed as large thumbnail in Zusam group and our grant parents will be happy ;)

**Comment by nrobinaubertin** [comment]
Feature added for impeding 0.2
