### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by lmolent** [nrobinaubertin/zusam#4]
Hi, after today's commit can't login to Zusam. 
Two types of errors are in a log files:

FastCGI sent in stderr: "PHP message: PHP Warning:  require(/srv/zusam/public/api/../../api/vendor/autoload.php): failed to open stream: No such file or directory in /srv/zusam/public/api/index.php on line 8

2019/04/08 07:42:59 [error] 28446#28446: *37 open() "/srv/zusam/public/sw.js" failed (2: No such file or directory)

**Comment by lmolent** [comment]
Aha, forget for composer install command. Sorry :)

**Comment by lmolent** [comment]
Still have problem to login:

ERROR for /api/login SyntaxError: Unexpected token < in JSON at position 0
    at app.61e2d9a8.js:8

**Comment by nrobinaubertin** [comment]
My bad: it's the first time that I have a project used by ther people :)
Don't consider master as stable for this one. Next time, I'll dev on a separate branch.

But your issue seems like an nginx issue: this error indicates that he's loading some kind of html instead of a JSON file

**Comment by lmolent** [comment]
No problem, I don't want stable branch :) 
Probably missing public/sw.js can cause this error (?):
# curl http://localhost/sw.js
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.14.2</center>
</body>
</html>

**Comment by nrobinaubertin** [comment]
No, there shouldn't be any sw.js (all the js comes packaged in the app.*.js file apart from language files).
Can you post you nginx config ? (at least the zusam server block ?)

**Comment by lmolent** [comment]
nginx config is pasted from your howto for debian:

```
# cat  /etc/nginx/sites-enabled/default 
server {
    listen 80;
    server_name _;
    port_in_redirect off;
    client_max_body_size 2048M;
    root /srv/zusam/public;
    location / {
        try_files $uri /index.html;
    }
    location ~ \.(js|png|css|woff2)$ {
        expires 1M;
        add_header Cache-Control "public";
    }
    location /files {
        expires 1M;
        try_files $uri =404;
    }
    location /api {
        try_files $uri /api/index.php$is_args$args;
    }
    location ~ ^/api/index\.php(/|$) {
        fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi.conf;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root/api;
        internal;
    }
    location ~ \.php$ {
        return 404;
    }
}
```
but in access.log I still have sw.js:
```
==> /var/log/nginx/access.log <==
192.168.1.7 - - [08/Apr/2019:08:10:15 +0000] "GET /sw.js HTTP/1.1" 404 199 "https://REMOVED/sw.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
```

**Comment by nrobinaubertin** [comment]
Yeah, the nginx conf seems good to me.
I don't understand what is calling that non-existent sw.js.

for your error:
```
ERROR for /api/login SyntaxError: Unexpected token < in JSON at position 0
at app.61e2d9a8.js:8
```
`/api/login` should return some json. There's maybe an issue on the symfony side.
Placing yourself into the api/ directory, try `php bin/console c:c`: this will reset symfony's cache and tell you if there's something wrong for him.
Can you double-check that file permissions are okay too ?

**Comment by lmolent** [comment]
Executed clear cache and checked permission mutiple times. After deleting data directory and executing zusam:init for create clear db it works. So tried to copy my old data directory and works too... I'm now confused why but anyway - it works :)

**Comment by nrobinaubertin** [comment]
Strange, I didn't change anything on the db side...
