### ISSUE TITLE
Notification email doesn't work

### ISSUE THREAD

**Issue by lmolent** [nrobinaubertin/zusam#9]
Hi,
notofication email for clean install from yesterday doesn't work and when I try `zusam:notification-emails` got:

```
# php /srv/zusam/api/bin/console zusam:notification-emails

10:00:39 WARNING   [php] Notice: Undefined variable: news ["exception" => ErrorException { …}]
10:00:39 WARNING   [php] Warning: count(): Parameter must be an array or an object that implements Countable ["exception" => ErrorException { …}]
```

**Comment by nrobinaubertin** [comment]
Good catch, thanks.
I think that https://github.com/nrobinaubertin/zusam/commit/cdbcbba809e12d19eb589d18f2c1d121b39c8ce5 should solve it.

**Comment by nrobinaubertin** [comment]
Closing. Feel free to reopen if the issue persists.
